name: Build Simulator
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  Linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Build"
        uses: ./.github/actions/build-simulator
        with:
          os_name: linux
          platform_name: amd64
          publish: true
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build"
        uses: ./.github/actions/build-simulator
        with:
          os_name: macos
          platform_name: aarch64
          publish: true
  Web:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Build"
        uses: ./.github/actions/build-simulator
        with:
          os_name: wasm
          platform_name: web
          publish: true
